-- Firebird schema generated from Laravel migrations.
-- Target: Firebird 3+ / 4+.
-- Notes:
-- 1. Boolean fields are SMALLINT with CHECK (field IN (0, 1)).
-- 2. JSON/text/longText are BLOB SUB_TYPE TEXT.
-- 3. Foreign keys are intentionally omitted to simplify bulk import. Add them after import if needed.
-- 4. Execute in a new/empty database.

CREATE TABLE plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255),
    description BLOB SUB_TYPE TEXT,
    price DECIMAL(10,2) DEFAULT 0,
    billing_months INTEGER DEFAULT 1 NOT NULL,
    status SMALLINT DEFAULT 1,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT chk_plans_status_bool CHECK (status IS NULL OR status IN (0, 1))
);

CREATE TABLE tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT,
    period_id BIGINT,
    name VARCHAR(255) NOT NULL,
    company VARCHAR(255),
    cpfcnpj VARCHAR(50),
    email VARCHAR(255),
    telephone VARCHAR(50),
    whatsapp VARCHAR(50),
    zipcode VARCHAR(50),
    state VARCHAR(50),
    city VARCHAR(50),
    district VARCHAR(50),
    street VARCHAR(80),
    number VARCHAR(50),
    complement VARCHAR(80),
    subscription_status VARCHAR(40) DEFAULT 'active',
    expires_at TIMESTAMP,
    last_subscription_notice_key VARCHAR(120),
    last_subscription_notice_sent_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    user_number INTEGER,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telephone VARCHAR(255),
    whatsapp VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    roles SMALLINT,
    status SMALLINT,
    email_verified_at TIMESTAMP,
    remember_token VARCHAR(100),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE password_reset_tokens (
    email VARCHAR(255) PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE sessions (
    id VARCHAR(255) PRIMARY KEY,
    user_id BIGINT,
    ip_address VARCHAR(45),
    user_agent BLOB SUB_TYPE TEXT,
    payload BLOB SUB_TYPE TEXT NOT NULL,
    last_activity INTEGER NOT NULL
);

CREATE TABLE cache (
    key VARCHAR(255) PRIMARY KEY,
    value BLOB SUB_TYPE TEXT NOT NULL,
    expiration INTEGER NOT NULL
);

CREATE TABLE cache_locks (
    key VARCHAR(255) PRIMARY KEY,
    owner VARCHAR(255) NOT NULL,
    expiration INTEGER NOT NULL
);

CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue VARCHAR(255) NOT NULL,
    payload BLOB SUB_TYPE TEXT NOT NULL,
    attempts SMALLINT NOT NULL,
    reserved_at INTEGER,
    available_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL
);

CREATE TABLE job_batches (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    total_jobs INTEGER NOT NULL,
    pending_jobs INTEGER NOT NULL,
    failed_jobs INTEGER NOT NULL,
    failed_job_ids BLOB SUB_TYPE TEXT NOT NULL,
    options BLOB SUB_TYPE TEXT,
    cancelled_at INTEGER,
    created_at INTEGER NOT NULL,
    finished_at INTEGER
);

CREATE TABLE failed_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL,
    connection BLOB SUB_TYPE TEXT NOT NULL,
    queue BLOB SUB_TYPE TEXT NOT NULL,
    payload BLOB SUB_TYPE TEXT NOT NULL,
    exception BLOB SUB_TYPE TEXT NOT NULL,
    failed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT,
    name VARCHAR(255) NOT NULL,
    months INTEGER DEFAULT 1,
    price DECIMAL(10,2) DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_id BIGINT,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    customer_number INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    cpfcnpj VARCHAR(50),
    birth DATE,
    email VARCHAR(50),
    zipcode VARCHAR(20),
    state VARCHAR(20),
    city VARCHAR(50),
    district VARCHAR(50),
    street VARCHAR(80),
    complement VARCHAR(80),
    number INTEGER,
    phone VARCHAR(20),
    contactname VARCHAR(50),
    whatsapp VARCHAR(255),
    contactphone VARCHAR(20),
    observations BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    equipment_number INTEGER NOT NULL,
    equipment VARCHAR(255) NOT NULL,
    chart SMALLINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT chk_equipment_chart_bool CHECK (chart IN (0, 1))
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    customer_id BIGINT,
    equipment_id BIGINT,
    user_id BIGINT,
    order_number INTEGER NOT NULL,
    tracking_token VARCHAR(40) NOT NULL,
    model VARCHAR(255),
    password VARCHAR(255),
    defect BLOB SUB_TYPE TEXT,
    state_conservation BLOB SUB_TYPE TEXT,
    accessories BLOB SUB_TYPE TEXT,
    budget_description BLOB SUB_TYPE TEXT,
    budget_value DECIMAL(10,2) DEFAULT 0,
    services_performed BLOB SUB_TYPE TEXT,
    parts_value DECIMAL(10,2) DEFAULT 0,
    service_value DECIMAL(10,2) DEFAULT 0,
    service_cost DECIMAL(10,2) DEFAULT 0,
    delivery_date DATE,
    delivery_forecast DATE,
    service_status INTEGER,
    observations BLOB SUB_TYPE TEXT,
    fiscal_document_number VARCHAR(120),
    fiscal_document_key VARCHAR(120),
    fiscal_document_url VARCHAR(255),
    fiscal_issued_at TIMESTAMP,
    fiscal_registered_by BIGINT,
    warranty_days INTEGER,
    warranty_expires_at TIMESTAMP,
    is_warranty_return SMALLINT DEFAULT 0,
    warranty_source_order_id BIGINT,
    budget_follow_up_paused_at TIMESTAMP,
    budget_follow_up_paused_by BIGINT,
    payment_follow_up_paused_at TIMESTAMP,
    payment_follow_up_paused_by BIGINT,
    budget_follow_up_response_status VARCHAR(40),
    budget_follow_up_responded_at TIMESTAMP,
    payment_follow_up_response_status VARCHAR(40),
    payment_follow_up_responded_at TIMESTAMP,
    budget_follow_up_snoozed_until TIMESTAMP,
    payment_follow_up_snoozed_until TIMESTAMP,
    budget_follow_up_assigned_to BIGINT,
    payment_follow_up_assigned_to BIGINT,
    customer_notification_acknowledged_at TIMESTAMP,
    customer_pickup_acknowledged_at TIMESTAMP,
    customer_feedback_rating INTEGER,
    customer_feedback_comment BLOB SUB_TYPE TEXT,
    customer_feedback_submitted_at TIMESTAMP,
    customer_feedback_recovery_assigned_to BIGINT,
    customer_feedback_recovery_status VARCHAR(40),
    customer_feedback_recovery_notes BLOB SUB_TYPE TEXT,
    customer_feedback_recovery_updated_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT chk_orders_warranty_return_bool CHECK (is_warranty_return IN (0, 1))
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    sender_id BIGINT,
    recipient_id BIGINT,
    message_number BIGINT,
    title BLOB SUB_TYPE TEXT NOT NULL,
    message BLOB SUB_TYPE TEXT NOT NULL,
    status SMALLINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT chk_messages_status_bool CHECK (status IN (0, 1))
);

CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    customer_id BIGINT,
    user_id BIGINT,
    schedules_number INTEGER NOT NULL,
    schedules TIMESTAMP NOT NULL,
    service VARCHAR(255) NOT NULL,
    details BLOB SUB_TYPE TEXT NOT NULL,
    status SMALLINT DEFAULT 1 NOT NULL,
    observations BLOB SUB_TYPE TEXT,
    responsible_technician VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    shortname VARCHAR(50),
    companyname VARCHAR(50),
    cnpj VARCHAR(50),
    logo VARCHAR(100),
    zip_code VARCHAR(50),
    state VARCHAR(50),
    city VARCHAR(50),
    district VARCHAR(50),
    street VARCHAR(50),
    number VARCHAR(50),
    complement VARCHAR(50),
    telephone VARCHAR(50),
    whatsapp VARCHAR(50),
    site VARCHAR(50),
    email VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE whatsapp_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    payment_reminder BLOB SUB_TYPE TEXT,
    budget_follow_up BLOB SUB_TYPE TEXT,
    warranty_follow_up BLOB SUB_TYPE TEXT,
    customer_feedback BLOB SUB_TYPE TEXT,
    default_message BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    title VARCHAR(255),
    description BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    budget_number BIGINT NOT NULL,
    equipment_id BIGINT NOT NULL,
    model VARCHAR(255),
    service VARCHAR(150) NOT NULL,
    description BLOB SUB_TYPE TEXT,
    estimated_time VARCHAR(50),
    part_value DECIMAL(10,2),
    labor_value DECIMAL(10,2) NOT NULL,
    total_value DECIMAL(10,2) NOT NULL,
    warranty VARCHAR(50),
    validity INTEGER,
    obs BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    equipment_id BIGINT,
    checklist_number INTEGER NOT NULL,
    checklist VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    equipment_id BIGINT,
    service_number INTEGER NOT NULL,
    service VARCHAR(255) NOT NULL,
    description BLOB SUB_TYPE TEXT,
    status SMALLINT DEFAULT 1,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT chk_services_status_bool CHECK (status IS NULL OR status IN (0, 1))
);

CREATE TABLE images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    order_id BIGINT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE others (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    navigation SMALLINT DEFAULT 0,
    enableparts SMALLINT DEFAULT 0,
    enablesales SMALLINT DEFAULT 0,
    warranty_return_alert_threshold DECIMAL(5,2) DEFAULT 15,
    communication_follow_up_cooldown_days INTEGER DEFAULT 3,
    budget_conversion_target DECIMAL(5,2) DEFAULT 40,
    payment_recovery_target DECIMAL(5,2) DEFAULT 70,
    customer_feedback_request_delay_days INTEGER DEFAULT 3,
    show_follow_ups_menu SMALLINT DEFAULT 0,
    show_tasks_menu SMALLINT DEFAULT 0,
    show_commercial_performance_menu SMALLINT DEFAULT 0,
    show_quality_menu SMALLINT DEFAULT 0,
    automatic_follow_ups_enabled SMALLINT DEFAULT 0,
    print_label_button_after_order_create SMALLINT DEFAULT 0,
    mail_mailer VARCHAR(255),
    mail_host VARCHAR(255),
    mail_port INTEGER,
    mail_username VARCHAR(255),
    mail_password VARCHAR(255),
    mail_encryption VARCHAR(255),
    mail_from_address VARCHAR(255),
    mail_from_name VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE personal_access_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tokenable_type VARCHAR(255) NOT NULL,
    tokenable_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    token VARCHAR(64) NOT NULL,
    abilities BLOB SUB_TYPE TEXT,
    last_used_at TIMESTAMP,
    expires_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    branch_number VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    zipcode VARCHAR(50),
    state VARCHAR(50),
    city VARCHAR(50),
    district VARCHAR(50),
    street VARCHAR(80),
    number VARCHAR(50),
    complement VARCHAR(80),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    name VARCHAR(255),
    logo VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    type VARCHAR(255) NOT NULL,
    is_sellable SMALLINT NOT NULL,
    category VARCHAR(255) NOT NULL,
    part_number VARCHAR(255) NOT NULL,
    reference_number VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description BLOB SUB_TYPE TEXT,
    manufacturer VARCHAR(255),
    model_compatibility BLOB SUB_TYPE TEXT,
    cost_price DECIMAL(10,2) NOT NULL,
    sale_price DECIMAL(10,2) NOT NULL,
    quantity INTEGER DEFAULT 0 NOT NULL,
    minimum_stock_level INTEGER DEFAULT 0 NOT NULL,
    location VARCHAR(255),
    status SMALLINT DEFAULT 1 NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT chk_parts_sellable_bool CHECK (is_sellable IN (0, 1)),
    CONSTRAINT chk_parts_status_bool CHECK (status IN (0, 1))
);

CREATE TABLE part_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    part_id BIGINT NOT NULL,
    order_id BIGINT,
    user_id BIGINT NOT NULL,
    movement_type VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    reason BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE order_parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    part_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE cash_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    opened_by BIGINT NOT NULL,
    closed_by BIGINT,
    opening_amount DECIMAL(10,2) DEFAULT 0 NOT NULL,
    closing_amount DECIMAL(10,2),
    expected_amount DECIMAL(10,2),
    difference_amount DECIMAL(10,2),
    status VARCHAR(20) DEFAULT 'open' NOT NULL,
    opened_at TIMESTAMP,
    closed_at TIMESTAMP,
    notes BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_number INTEGER NOT NULL,
    tenant_id BIGINT NOT NULL,
    customer_id BIGINT,
    cash_session_id BIGINT,
    total_amount DECIMAL(10,2) NOT NULL,
    paid_amount DECIMAL(10,2) DEFAULT 0 NOT NULL,
    financial_status VARCHAR(30) DEFAULT 'paid' NOT NULL,
    payment_method VARCHAR(50) DEFAULT 'cash' NOT NULL,
    status VARCHAR(50) DEFAULT 'completed' NOT NULL,
    cancel_reason BLOB SUB_TYPE TEXT,
    cancelled_at TIMESTAMP,
    cancelled_by BIGINT,
    fiscal_document_number VARCHAR(120),
    fiscal_document_key VARCHAR(120),
    fiscal_document_url VARCHAR(255),
    fiscal_issued_at TIMESTAMP,
    fiscal_registered_by BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    part_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    payment_id VARCHAR(255) NOT NULL,
    gateway VARCHAR(50) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    payload BLOB SUB_TYPE TEXT,
    expires_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    status INTEGER NOT NULL,
    note BLOB SUB_TYPE TEXT,
    changed_by BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE order_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    cash_session_id BIGINT,
    payment_method VARCHAR(50),
    amount DECIMAL(10,2) NOT NULL,
    paid_at TIMESTAMP,
    notes BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE order_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    user_id BIGINT,
    action VARCHAR(255) NOT NULL,
    data BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE sale_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    user_id BIGINT,
    action VARCHAR(255) NOT NULL,
    data BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    created_by BIGINT,
    expense_number INTEGER,
    description VARCHAR(255) NOT NULL,
    category VARCHAR(255),
    amount DECIMAL(10,2) NOT NULL,
    expense_date DATE NOT NULL,
    payment_method VARCHAR(50),
    notes BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE cash_session_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    cash_session_id BIGINT NOT NULL,
    user_id BIGINT,
    action VARCHAR(255) NOT NULL,
    data BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE expense_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    expense_id BIGINT NOT NULL,
    user_id BIGINT,
    action VARCHAR(255) NOT NULL,
    data BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE operational_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT,
    action VARCHAR(255) NOT NULL,
    entity_type VARCHAR(255) NOT NULL,
    entity_id BIGINT NOT NULL,
    data BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE tenant_feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    feedback_token CHAR(36) NOT NULL,
    feedback_source VARCHAR(80) NOT NULL,
    feedback_status VARCHAR(40) NOT NULL,
    rating INTEGER,
    comment BLOB SUB_TYPE TEXT,
    feedback_submitted_at TIMESTAMP,
    feedback_recovery_status VARCHAR(40),
    feedback_recovery_assigned_to BIGINT,
    feedback_recovery_notes BLOB SUB_TYPE TEXT,
    feedback_recovery_updated_at TIMESTAMP,
    testimonial_author VARCHAR(255),
    testimonial_role VARCHAR(255),
    testimonial_company VARCHAR(255),
    testimonial_quote BLOB SUB_TYPE TEXT,
    testimonial_status VARCHAR(40),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE tenant_improvement_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT,
    request_type VARCHAR(80) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description BLOB SUB_TYPE TEXT NOT NULL,
    status VARCHAR(40) DEFAULT 'pending' NOT NULL,
    admin_notes BLOB SUB_TYPE TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE fiscal_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    provider VARCHAR(50),
    environment VARCHAR(50),
    api_token BLOB SUB_TYPE TEXT,
    certificate_path VARCHAR(255),
    certificate_password VARCHAR(255),
    company_tax_id VARCHAR(50),
    municipal_registration VARCHAR(80),
    state_registration VARCHAR(80),
    service_code VARCHAR(80),
    municipal_tax_code VARCHAR(80),
    cnae VARCHAR(30),
    iss_rate DECIMAL(8,4),
    nfe_enabled SMALLINT DEFAULT 0,
    nfse_enabled SMALLINT DEFAULT 0,
    enabled SMALLINT DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT chk_fiscal_settings_nfe_bool CHECK (nfe_enabled IN (0, 1)),
    CONSTRAINT chk_fiscal_settings_nfse_bool CHECK (nfse_enabled IN (0, 1)),
    CONSTRAINT chk_fiscal_settings_enabled_bool CHECK (enabled IN (0, 1))
);

CREATE TABLE fiscal_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    documentable_type VARCHAR(255) NOT NULL,
    documentable_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(50) NOT NULL,
    number VARCHAR(120),
    document_key VARCHAR(120),
    document_url VARCHAR(255),
    provider VARCHAR(50),
    provider_reference VARCHAR(255),
    request_payload BLOB SUB_TYPE TEXT,
    response_payload BLOB SUB_TYPE TEXT,
    error_message BLOB SUB_TYPE TEXT,
    issued_at TIMESTAMP,
    registered_by BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- Unique constraints and indexes.
CREATE UNIQUE INDEX users_email_unique ON users (email);
CREATE INDEX sessions_user_id_idx ON sessions (user_id);
CREATE INDEX sessions_last_activity_idx ON sessions (last_activity);
CREATE INDEX jobs_queue_idx ON jobs (queue);
CREATE UNIQUE INDEX failed_jobs_uuid_unique ON failed_jobs (uuid);
CREATE INDEX plans_slug_idx ON plans (slug);
CREATE INDEX tenants_subscription_expires_idx ON tenants (subscription_status, expires_at);
CREATE INDEX users_tenant_roles_status_idx ON users (tenant_id, roles, status);
CREATE INDEX customers_tenant_number_idx ON customers (tenant_id, customer_number);
CREATE INDEX orders_tenant_status_created_idx ON orders (tenant_id, service_status, created_at);
CREATE INDEX orders_tenant_customer_created_idx ON orders (tenant_id, customer_id, created_at);
CREATE INDEX orders_tenant_created_idx ON orders (tenant_id, created_at);
CREATE UNIQUE INDEX orders_tracking_token_unique ON orders (tracking_token);
CREATE UNIQUE INDEX orders_tenant_order_number_unique ON orders (tenant_id, order_number);
CREATE INDEX messages_recipient_status_id_idx ON messages (recipient_id, status, id);
CREATE INDEX messages_sender_id_idx ON messages (sender_id, id);
CREATE INDEX schedules_tenant_status_id_idx ON schedules (tenant_id, status, id);
CREATE INDEX schedules_tenant_datetime_idx ON schedules (tenant_id, schedules);
CREATE INDEX budgets_tenant_number_idx ON budgets (tenant_id, budget_number);
CREATE INDEX checklists_tenant_number_idx ON checklists (tenant_id, checklist_number);
CREATE INDEX services_tenant_number_idx ON services (tenant_id, service_number);
CREATE UNIQUE INDEX parts_category_unique ON parts (category);
CREATE UNIQUE INDEX parts_tenant_part_number_unique ON parts (tenant_id, part_number);
CREATE UNIQUE INDEX parts_tenant_reference_number_unique ON parts (tenant_id, reference_number);
CREATE INDEX parts_tenant_type_created_idx ON parts (tenant_id, type, created_at);
CREATE INDEX parts_tenant_sellable_idx ON parts (tenant_id, is_sellable);
CREATE INDEX part_movements_tenant_part_created_idx ON part_movements (tenant_id, part_id, created_at);
CREATE INDEX part_movements_order_created_idx ON part_movements (order_id, created_at);
CREATE INDEX sales_tenant_number_idx ON sales (tenant_id, sales_number);
CREATE INDEX sales_tenant_status_created_idx ON sales (tenant_id, status, created_at);
CREATE INDEX sales_tenant_cash_session_idx ON sales (tenant_id, cash_session_id);
CREATE INDEX sales_tenant_payment_method_idx ON sales (tenant_id, payment_method);
CREATE INDEX sales_tenant_cancelled_idx ON sales (tenant_id, status, cancelled_at);
CREATE INDEX sales_tenant_financial_status_idx ON sales (tenant_id, financial_status);
CREATE INDEX sale_items_sale_part_idx ON sale_items (sale_id, part_id);
CREATE UNIQUE INDEX payments_payment_id_unique ON payments (payment_id);
CREATE UNIQUE INDEX payments_idempotency_key_unique ON payments (idempotency_key);
CREATE INDEX payments_tenant_status_created_idx ON payments (tenant_id, status, created_at);
CREATE INDEX payments_gateway_status_idx ON payments (gateway, status);
CREATE INDEX payments_expires_at_idx ON payments (expires_at);
CREATE INDEX order_status_history_order_created_idx ON order_status_history (order_id, created_at);
CREATE INDEX order_payments_order_paid_at_idx ON order_payments (order_id, paid_at);
CREATE INDEX order_payments_cash_paid_at_idx ON order_payments (cash_session_id, paid_at);
CREATE INDEX order_logs_order_created_idx ON order_logs (order_id, created_at);
CREATE INDEX cash_sessions_tenant_status_idx ON cash_sessions (tenant_id, status);
CREATE INDEX cash_sessions_tenant_opened_at_idx ON cash_sessions (tenant_id, opened_at);
CREATE INDEX sale_logs_sale_created_idx ON sale_logs (sale_id, created_at);
CREATE INDEX expenses_tenant_expense_date_idx ON expenses (tenant_id, expense_date);
CREATE INDEX expenses_tenant_category_idx ON expenses (tenant_id, category);
CREATE UNIQUE INDEX expenses_tenant_number_unique ON expenses (tenant_id, expense_number);
CREATE INDEX cash_session_logs_session_created_idx ON cash_session_logs (cash_session_id, created_at);
CREATE INDEX expense_logs_expense_created_idx ON expense_logs (expense_id, created_at);
CREATE INDEX operational_audits_entity_idx ON operational_audits (tenant_id, entity_type, entity_id);
CREATE INDEX operational_audits_action_idx ON operational_audits (tenant_id, action, created_at);
CREATE UNIQUE INDEX tenant_feedbacks_token_unique ON tenant_feedbacks (feedback_token);
CREATE INDEX tenant_feedbacks_status_idx ON tenant_feedbacks (tenant_id, feedback_status);
CREATE INDEX tenant_feedbacks_source_status_idx ON tenant_feedbacks (feedback_source, feedback_status);
CREATE INDEX tenant_feedbacks_submitted_idx ON tenant_feedbacks (feedback_submitted_at);
CREATE INDEX tenant_feedbacks_recovery_status_idx ON tenant_feedbacks (feedback_recovery_status);
CREATE INDEX tenant_feedbacks_testimonial_status_idx ON tenant_feedbacks (testimonial_status);
CREATE INDEX tenant_improvement_requests_tenant_status_idx ON tenant_improvement_requests (tenant_id, status);
CREATE INDEX tenant_improvement_requests_type_status_idx ON tenant_improvement_requests (request_type, status);
CREATE UNIQUE INDEX fiscal_settings_tenant_unique ON fiscal_settings (tenant_id);
CREATE INDEX fiscal_documents_tenant_type_status_idx ON fiscal_documents (tenant_id, type, status);
CREATE INDEX fiscal_documents_documentable_idx ON fiscal_documents (documentable_type, documentable_id);
CREATE UNIQUE INDEX personal_access_tokens_token_unique ON personal_access_tokens (token);
CREATE INDEX personal_access_tokens_tokenable_idx ON personal_access_tokens (tokenable_type, tokenable_id);

COMMIT;
